export type CuratedTool = {
  id: string;
  name: string;
  slug: string;
  tagline_bn: string;
  description_bn: string;
  pricing: "free" | "freemium" | "paid" | "enterprise";
  pricing_type: "free" | "freemium" | "paid" | "enterprise";
  website_url: string;
  logo_url: string;
  status: "published";
  category_slug: string;
  categories: { name_bn: string; slug: string; icon: string };
  use_cases: string[];
  features_bn: string[];
  pros: string[];
  cons: string[];
  faq: { q: string; a: string }[];
  best_for_bn?: string[];
  bd_use_cases_bn?: string[];
  workflow_bn?: string[];
  setup_steps_bn?: string[];
  limitations_bn?: string[];
  selection_tips_bn?: string[];
  badge?: string;
  rating: number;
  review_count: number;
  view_count: number;
};

export const TOOL_USE_CASES = [
  { key: "writing", label: "লেখালেখি", icon: "✍️", query: "AI writing", hint: "ব্লগ, কপি, ইমেইল, স্ক্রিপ্ট" },
  { key: "research", label: "রিসার্চ", icon: "🔎", query: "AI research", hint: "সোর্সসহ দ্রুত উত্তর" },
  { key: "image", label: "ইমেজ", icon: "🎨", query: "AI image", hint: "থাম্বনেইল, পোস্টার, ব্র্যান্ড ভিজ্যুয়াল" },
  { key: "video", label: "ভিডিও", icon: "🎬", query: "AI video", hint: "রিলস, এডিটিং, জেনারেটিভ ভিডিও" },
  { key: "voice", label: "ভয়েস", icon: "🎙️", query: "AI voice", hint: "ভয়েসওভার, ডাবিং, অডিও" },
  { key: "coding", label: "কোডিং", icon: "💻", query: "AI coding", hint: "কোড লেখা, রিভিউ, ডিবাগ" },
  { key: "automation", label: "অটোমেশন", icon: "⚙️", query: "AI automation", hint: "ওয়ার্কফ্লো, ফর্ম, CRM, নোটিফিকেশন" },
  { key: "presentation", label: "প্রেজেন্টেশন", icon: "📊", query: "AI presentation", hint: "স্লাইড, পিচ ডেক, রিপোর্ট" },
];

export const CURATED_TOOLS: CuratedTool[] = [
  {
    id: "curated-chatgpt",
    name: "ChatGPT",
    slug: "chatgpt",
    tagline_bn: "লেখালেখি, আইডিয়া, কোডিং ও দৈনন্দিন AI সহকারীর জন্য জনপ্রিয় টুল।",
    description_bn:
      "ChatGPT সাধারণ AI assistant হিসেবে কনটেন্ট আইডিয়া, বাংলা-ইংরেজি ড্রাফট, কোড ব্যাখ্যা, রিসার্চ প্ল্যান এবং প্রোডাক্টিভিটি কাজে ব্যবহার করা যায়। ফ্রিল্যান্সার, স্টুডেন্ট ও ছোট টিমের জন্য এটি দ্রুত শুরু করার মতো একটি বহুমুখী টুল।",
    pricing: "freemium",
    pricing_type: "freemium",
    website_url: "https://chatgpt.com/",
    logo_url: "",
    status: "published",
    category_slug: "ai-productivity",
    categories: { name_bn: "প্রোডাক্টিভিটি", slug: "ai-productivity", icon: "⚡" },
    use_cases: ["writing", "research", "coding"],
    features_bn: ["কনটেন্ট ড্রাফট ও আইডিয়া", "কোড ব্যাখ্যা ও ডিবাগিং সহায়তা", "ডকুমেন্ট সারাংশ ও পরিকল্পনা"],
    pros: ["বহুমুখী কাজে ব্যবহারযোগ্য", "শুরু করা সহজ", "বাংলা প্রম্পটেও কাজ করে"],
    cons: ["গুরুত্বপূর্ণ তথ্য আলাদা করে যাচাই করা দরকার", "দীর্ঘ কাজের জন্য পরিষ্কার প্রম্পট লাগে"],
    faq: [
      { q: "ChatGPT কোন কাজে ভালো?", a: "লেখালেখি, আইডিয়া, কোড ব্যাখ্যা, রিসার্চ প্ল্যান এবং দৈনন্দিন productivity কাজে ভালো।" },
      { q: "বাংলায় ব্যবহার করা যায়?", a: "হ্যাঁ, বাংলা নির্দেশনা দিয়ে ড্রাফট, সারাংশ ও পরিকল্পনা তৈরি করা যায়।" },
    ],
    badge: "popular",
    rating: 4.8,
    review_count: 1,
    view_count: 0,
  },
  {
    id: "curated-claude",
    name: "Claude",
    slug: "claude",
    tagline_bn: "লম্বা ডকুমেন্ট, বিশ্লেষণ, রাইটিং ও কোডিং কাজে শক্তিশালী AI assistant।",
    description_bn:
      "Claude বড় ডকুমেন্ট পড়া, লেখা পরিষ্কার করা, বিশ্লেষণ, কোডিং আইডিয়া এবং structured output তৈরির কাজে ব্যবহারযোগ্য। লম্বা context নিয়ে কাজ করতে হলে এটি ভালো বিকল্প।",
    pricing: "freemium",
    pricing_type: "freemium",
    website_url: "https://claude.ai/",
    logo_url: "",
    status: "published",
    category_slug: "ai-productivity",
    categories: { name_bn: "প্রোডাক্টিভিটি", slug: "ai-productivity", icon: "⚡" },
    use_cases: ["writing", "research", "coding"],
    features_bn: ["লম্বা ডকুমেন্ট বিশ্লেষণ", "রাইটিং স্ট্রাকচার উন্নত করা", "কোড ও টেকনিক্যাল ব্যাখ্যা"],
    pros: ["লম্বা লেখায় ভালো", "পরিষ্কার উত্তর দেয়", "ডকুমেন্টভিত্তিক কাজে শক্তিশালী"],
    cons: ["সব দেশে/প্ল্যানে একই সুবিধা নাও থাকতে পারে", "ফ্যাক্ট যাচাই দরকার"],
    faq: [{ q: "Claude কার জন্য?", a: "রাইটার, রিসার্চার, ডেভেলপার এবং যারা লম্বা ডকুমেন্ট নিয়ে কাজ করেন তাদের জন্য।" }],
    badge: "editors_choice",
    rating: 4.7,
    review_count: 1,
    view_count: 0,
  },
  {
    id: "curated-perplexity",
    name: "Perplexity",
    slug: "perplexity",
    tagline_bn: "সোর্সসহ দ্রুত রিসার্চ ও প্রশ্নের উত্তর খোঁজার জন্য AI সার্চ টুল।",
    description_bn:
      "Perplexity দ্রুত web research, citationসহ answer, টপিক সারাংশ এবং comparison করার কাজে সহায়ক। ব্লগ, YouTube script বা client research শুরু করার আগে source discovery করতে কাজে লাগে।",
    pricing: "freemium",
    pricing_type: "freemium",
    website_url: "https://www.perplexity.ai/",
    logo_url: "",
    status: "published",
    category_slug: "ai-research",
    categories: { name_bn: "রিসার্চ", slug: "ai-research", icon: "🔎" },
    use_cases: ["research", "writing"],
    features_bn: ["সোর্সসহ উত্তর", "দ্রুত টপিক সারাংশ", "রিসার্চ query follow-up"],
    pros: ["রিসার্চ শুরু করতে দ্রুত", "citation দেখা যায়", "comparison কাজে সুবিধাজনক"],
    cons: ["সোর্স নিজে পড়ে যাচাই করা উচিত", "সব উত্তর final ধরে নেওয়া যাবে না"],
    faq: [{ q: "Perplexity কি Google-এর বিকল্প?", a: "পুরোপুরি নয়; এটি AI-assisted research assistant হিসেবে ভালো, কিন্তু source verification দরকার।" }],
    badge: "trending",
    rating: 4.6,
    review_count: 1,
    view_count: 0,
  },
  {
    id: "curated-canva-magic-studio",
    name: "Canva Magic Studio",
    slug: "canva-magic-studio",
    tagline_bn: "ডিজাইন, সোশ্যাল পোস্ট, প্রেজেন্টেশন ও মার্কেটিং ভিজ্যুয়ালের জন্য AI design suite।",
    description_bn:
      "Canva Magic Studio non-designer users-দের জন্য দ্রুত পোস্টার, social creative, presentation, thumbnail এবং marketing visual বানাতে সাহায্য করে। ছোট ব্যবসা ও creator workflow-তে এটি ব্যবহারযোগ্য।",
    pricing: "freemium",
    pricing_type: "freemium",
    website_url: "https://www.canva.com/magic/",
    logo_url: "",
    status: "published",
    category_slug: "ai-design",
    categories: { name_bn: "ডিজাইন", slug: "ai-design", icon: "🎨" },
    use_cases: ["image", "presentation", "writing"],
    features_bn: ["AI design generation", "প্রেজেন্টেশন ও social template", "ইমেজ ও কপি সহায়তা"],
    pros: ["শুরু করা সহজ", "টেমপ্লেট ecosystem বড়", "টিমের জন্য practical"],
    cons: ["সব advanced asset free নাও হতে পারে", "brand consistency নিজে ঠিক করতে হয়"],
    faq: [{ q: "কোন কাজে ব্যবহার করব?", a: "Facebook পোস্ট, থাম্বনেইল, প্রেজেন্টেশন, ব্যানার এবং basic brand creative বানাতে।" }],
    badge: "popular",
    rating: 4.6,
    review_count: 1,
    view_count: 0,
  },
  {
    id: "curated-capcut",
    name: "CapCut",
    slug: "capcut",
    tagline_bn: "রিলস, শর্টস, caption, template ও AI video editing-এর জন্য সহজ টুল।",
    description_bn:
      "CapCut creator ও small business team-দের জন্য short-form video edit, caption, template, background remove এবং AI-powered creative কাজে ব্যবহারযোগ্য। দ্রুত social video বানাতে এটি ভালো starting point।",
    pricing: "freemium",
    pricing_type: "freemium",
    website_url: "https://www.capcut.com/",
    logo_url: "",
    status: "published",
    category_slug: "ai-video",
    categories: { name_bn: "ভিডিও", slug: "ai-video", icon: "🎬" },
    use_cases: ["video"],
    features_bn: ["ভিডিও এডিটিং ও template", "caption ও audio tools", "সোশ্যাল ভিডিও workflow"],
    pros: ["রিলস/শর্টস বানানো সহজ", "অনেক ready template", "মোবাইল workflow ভালো"],
    cons: ["ভালো result-এর জন্য manual edit লাগে", "কিছু feature paid হতে পারে"],
    faq: [{ q: "CapCut কার জন্য?", a: "Creator, marketer, small business এবং social video editor-দের জন্য।" }],
    badge: "popular",
    rating: 4.5,
    review_count: 1,
    view_count: 0,
  },
  {
    id: "curated-runway",
    name: "Runway",
    slug: "runway",
    tagline_bn: "জেনারেটিভ ভিডিও, image-to-video ও creative AI production-এর জন্য advanced টুল।",
    description_bn:
      "Runway creative video generation, image-to-video, editing এবং experimental visual production workflow-তে ব্যবহার করা হয়। ad concept, music video, storyboard বা creative demo বানাতে কাজে লাগতে পারে।",
    pricing: "freemium",
    pricing_type: "freemium",
    website_url: "https://runwayml.com/",
    logo_url: "",
    status: "published",
    category_slug: "ai-video",
    categories: { name_bn: "ভিডিও", slug: "ai-video", icon: "🎬" },
    use_cases: ["video", "image"],
    features_bn: ["জেনারেটিভ ভিডিও", "image-to-video workflow", "creative editing tools"],
    pros: ["creative output শক্তিশালী", "ভিডিও ideation দ্রুত", "প্রোডাকশন demo-তে ভালো"],
    cons: ["প্রম্পট ও iteration দরকার", "commercial work-এর আগে rights/policy দেখা উচিত"],
    faq: [{ q: "Runway কি beginner-friendly?", a: "Basic কাজ শুরু করা যায়, কিন্তু ভালো result-এর জন্য prompt, reference ও edit workflow দরকার।" }],
    badge: "trending",
    rating: 4.5,
    review_count: 1,
    view_count: 0,
  },
  {
    id: "curated-elevenlabs",
    name: "ElevenLabs",
    slug: "elevenlabs",
    tagline_bn: "AI voiceover, text-to-speech, dubbing ও audio content-এর জন্য জনপ্রিয় ভয়েস টুল।",
    description_bn:
      "ElevenLabs text-to-speech, voiceover, dubbing এবং audio narration workflow-তে ব্যবহার করা যায়। YouTube, course, podcast snippet বা product demo voice বানাতে কাজে লাগে।",
    pricing: "freemium",
    pricing_type: "freemium",
    website_url: "https://elevenlabs.io/",
    logo_url: "",
    status: "published",
    category_slug: "ai-audio",
    categories: { name_bn: "অডিও", slug: "ai-audio", icon: "🎙️" },
    use_cases: ["voice", "video"],
    features_bn: ["Text-to-speech", "Voiceover ও narration", "Dubbing workflow"],
    pros: ["ভয়েস quality ভালো", "ভিডিও কনটেন্টে useful", "দ্রুত narration তৈরি করা যায়"],
    cons: ["ভয়েস cloning ব্যবহারে consent জরুরি", "বাংলা/উচ্চারণ result test করা উচিত"],
    faq: [{ q: "ElevenLabs কী কাজে ভালো?", a: "Voiceover, narration, dubbing এবং audio-first content তৈরিতে।" }],
    badge: "editors_choice",
    rating: 4.6,
    review_count: 1,
    view_count: 0,
  },
  {
    id: "curated-cursor",
    name: "Cursor",
    slug: "cursor",
    tagline_bn: "AI-powered code editor, codebase chat, refactor ও debugging workflow-এর জন্য।",
    description_bn:
      "Cursor developer-দের জন্য AI coding assistant সহ editor experience দেয়। codebase বুঝে প্রশ্ন করা, refactor, test generation এবং bug fixing workflow দ্রুত করতে ব্যবহার করা যায়।",
    pricing: "freemium",
    pricing_type: "freemium",
    website_url: "https://www.cursor.com/",
    logo_url: "",
    status: "published",
    category_slug: "ai-development",
    categories: { name_bn: "ডেভেলপমেন্ট", slug: "ai-development", icon: "💻" },
    use_cases: ["coding", "automation"],
    features_bn: ["Codebase chat", "AI-assisted editing", "Refactor ও debugging support"],
    pros: ["ডেভেলপার workflow-তে সরাসরি কাজ করে", "বড় codebase বুঝতে সাহায্য করে", "প্রোটোটাইপ দ্রুত হয়"],
    cons: ["AI output review না করলে bug আসতে পারে", "privacy-sensitive code নিয়ে policy দেখা দরকার"],
    faq: [{ q: "Cursor কি VS Code-এর বিকল্প?", a: "অনেক ক্ষেত্রে VS Code-like workflow-এর সাথে AI coding সুবিধা দেয়, তবে team policy অনুযায়ী ব্যবহার করা উচিত।" }],
    badge: "trending",
    rating: 4.7,
    review_count: 1,
    view_count: 0,
  },
  {
    id: "curated-zapier-ai",
    name: "Zapier AI",
    slug: "zapier-ai",
    tagline_bn: "অ্যাপ সংযোগ, repetitive task automation ও AI workflow তৈরির জন্য।",
    description_bn:
      "Zapier AI apps connect করে lead capture, notification, CRM update, content workflow এবং internal automation বানাতে সাহায্য করে। non-technical team-ও basic automation শুরু করতে পারে।",
    pricing: "freemium",
    pricing_type: "freemium",
    website_url: "https://zapier.com/ai",
    logo_url: "",
    status: "published",
    category_slug: "ai-automation",
    categories: { name_bn: "অটোমেশন", slug: "ai-automation", icon: "⚙️" },
    use_cases: ["automation"],
    features_bn: ["App-to-app automation", "AI workflow assistant", "Lead ও notification process"],
    pros: ["অনেক app integration", "no-code workflow সহজ", "ব্যবসায়িক process automate করা যায়"],
    cons: ["Complex flow-তে planning দরকার", "usage limit ও cost আগে দেখা উচিত"],
    faq: [{ q: "Zapier AI কী কাজে ব্যবহার করব?", a: "Form submission, email, spreadsheet, CRM, Slack/Telegram notification এবং repetitive task automate করতে।" }],
    badge: "best_value",
    rating: 4.4,
    review_count: 1,
    view_count: 0,
  },
  {
    id: "curated-grammarly",
    name: "Grammarly",
    slug: "grammarly",
    tagline_bn: "ইংরেজি writing, grammar, tone ও communication polish করার জন্য AI writing assistant।",
    description_bn:
      "Grammarly email, proposal, blog draft, academic writing এবং client communication পরিষ্কার করতে সাহায্য করে। বাংলাদেশি freelancer-দের ইংরেজি proposal polish করার কাজে এটি practical।",
    pricing: "freemium",
    pricing_type: "freemium",
    website_url: "https://www.grammarly.com/",
    logo_url: "",
    status: "published",
    category_slug: "ai-writing",
    categories: { name_bn: "রাইটিং", slug: "ai-writing", icon: "✍️" },
    use_cases: ["writing"],
    features_bn: ["Grammar ও spelling suggestion", "Tone improvement", "ইমেইল ও proposal polish"],
    pros: ["Client communication-এ useful", "Browser/editor integration আছে", "ইংরেজি writing দ্রুত polish হয়"],
    cons: ["সব suggestion blindly নেওয়া ঠিক না", "বাংলা writing-এর জন্য primary tool নয়"],
    faq: [{ q: "Grammarly কার জন্য?", a: "ইংরেজিতে email, proposal, article বা academic draft লেখেন এমন ব্যবহারকারীদের জন্য।" }],
    badge: "popular",
    rating: 4.4,
    review_count: 1,
    view_count: 0,
  },
  {
    id: "curated-gemini",
    name: "Gemini",
    slug: "gemini",
    tagline_bn: "Google ecosystem, research, writing, image understanding ও productivity কাজের জন্য AI assistant।",
    description_bn:
      "Gemini Google Search, Docs, Gmail, Drive এবং Android workflow-এর সাথে পরিচিত ব্যবহারকারীদের জন্য practical AI assistant। research summary, email draft, data explanation, image understanding এবং everyday productivity কাজে এটি ভালো fit। Google Workspace ব্যবহার করলে team workflow-তেও value পাওয়া যায়।",
    pricing: "freemium",
    pricing_type: "freemium",
    website_url: "https://gemini.google.com/",
    logo_url: "",
    status: "published",
    category_slug: "ai-productivity",
    categories: { name_bn: "প্রোডাক্টিভিটি", slug: "ai-productivity", icon: "⚡" },
    use_cases: ["writing", "research", "automation"],
    features_bn: ["Google ecosystem integration", "লেখা, সারাংশ ও planning", "image ও document understanding"],
    pros: ["Google user-দের জন্য familiar", "research workflow সহজ", "মাল্টিমোডাল কাজে useful"],
    cons: ["সব feature সব region/plan-এ নাও থাকতে পারে", "critical facts verify করা দরকার"],
    faq: [{ q: "Gemini কাদের জন্য ভালো?", a: "যারা Google tools ব্যবহার করেন এবং writing, research, document summary বা productivity কাজ করেন।" }],
    badge: "popular",
    rating: 4.6,
    review_count: 1,
    view_count: 0,
  },
  {
    id: "curated-copilot",
    name: "Microsoft Copilot",
    slug: "microsoft-copilot",
    tagline_bn: "Office, Windows, Bing research ও business productivity workflow-এর জন্য AI assistant।",
    description_bn:
      "Microsoft Copilot Word, Excel, PowerPoint, Outlook এবং Windows ecosystem-এর ব্যবহারকারীদের জন্য AI productivity assistant। document draft, meeting summary, spreadsheet analysis, slide outline এবং business communication polish করার কাজে এটি valuable।",
    pricing: "freemium",
    pricing_type: "freemium",
    website_url: "https://copilot.microsoft.com/",
    logo_url: "",
    status: "published",
    category_slug: "ai-productivity",
    categories: { name_bn: "প্রোডাক্টিভিটি", slug: "ai-productivity", icon: "⚡" },
    use_cases: ["writing", "research", "presentation"],
    features_bn: ["Office workflow support", "Web research assistant", "Document ও presentation drafting"],
    pros: ["Business workflow-এ practical", "Office users-দের জন্য useful", "Research + writing একসাথে করা যায়"],
    cons: ["Best value পেতে Microsoft ecosystem দরকার", "Sensitive company data policy দেখে ব্যবহার করা উচিত"],
    faq: [{ q: "Copilot কি business use-এর জন্য ভালো?", a: "হ্যাঁ, বিশেষ করে Microsoft 365 workflow থাকলে document, email, spreadsheet ও slide কাজে ভালো।" }],
    badge: "popular",
    rating: 4.5,
    review_count: 1,
    view_count: 0,
  },
  {
    id: "curated-deepseek",
    name: "DeepSeek",
    slug: "deepseek",
    tagline_bn: "Coding, reasoning ও technical problem-solving কাজে popular AI model/chat assistant।",
    description_bn:
      "DeepSeek coding help, math/reasoning, technical explanation এবং software planning কাজে ব্যবহারযোগ্য। developer, student ও technical writer-দের জন্য low-cost বা free experimentation workflow-তে এটি কাজে লাগে।",
    pricing: "freemium",
    pricing_type: "freemium",
    website_url: "https://www.deepseek.com/",
    logo_url: "",
    status: "published",
    category_slug: "ai-development",
    categories: { name_bn: "ডেভেলপমেন্ট", slug: "ai-development", icon: "💻" },
    use_cases: ["coding", "research"],
    features_bn: ["Coding explanation", "Reasoning-heavy answer", "Technical planning ও debugging support"],
    pros: ["Technical tasks-এ শক্তিশালী", "Experiment করা সহজ", "Code learning-এ useful"],
    cons: ["Production code review ছাড়া merge করা ঠিক না", "Privacy-sensitive data input এড়ানো ভালো"],
    faq: [{ q: "DeepSeek কোন কাজে ব্যবহার করব?", a: "Coding, algorithm explanation, debugging idea এবং technical research draft তৈরিতে।" }],
    badge: "trending",
    rating: 4.5,
    review_count: 1,
    view_count: 0,
  },
  {
    id: "curated-midjourney",
    name: "Midjourney",
    slug: "midjourney",
    tagline_bn: "High-quality AI image, concept art, product visual ও creative campaign image তৈরির জন্য।",
    description_bn:
      "Midjourney creative image generation-এর জন্য premium-quality output দেয়। brand moodboard, ad concept, book cover, thumbnail idea, character concept এবং visual exploration workflow-তে এটি খুব শক্তিশালী।",
    pricing: "paid",
    pricing_type: "paid",
    website_url: "https://www.midjourney.com/",
    logo_url: "",
    status: "published",
    category_slug: "ai-design",
    categories: { name_bn: "ডিজাইন", slug: "ai-design", icon: "🎨" },
    use_cases: ["image"],
    features_bn: ["Premium image generation", "Style ও art direction control", "Concept visual exploration"],
    pros: ["Image quality খুব ভালো", "Creative direction দ্রুত test করা যায়", "Marketing visual ideation-এ শক্তিশালী"],
    cons: ["Prompt skill দরকার", "Commercial rights/plan terms আগে দেখা উচিত"],
    faq: [{ q: "Midjourney কি Canva-এর বিকল্প?", a: "না, Midjourney image generation-এ শক্তিশালী; Canva layout/design publishing workflow-তে সহজ।" }],
    badge: "editors_choice",
    rating: 4.8,
    review_count: 1,
    view_count: 0,
  },
  {
    id: "curated-leonardo-ai",
    name: "Leonardo AI",
    slug: "leonardo-ai",
    tagline_bn: "Game asset, product mockup, character ও marketing image তৈরির জন্য AI image platform।",
    description_bn:
      "Leonardo AI image generation, style preset, asset creation এবং creative iteration workflow-তে useful। যারা social creative, product mockup বা game/character asset নিয়ে কাজ করেন তাদের জন্য এটি practical alternative।",
    pricing: "freemium",
    pricing_type: "freemium",
    website_url: "https://leonardo.ai/",
    logo_url: "",
    status: "published",
    category_slug: "ai-design",
    categories: { name_bn: "ডিজাইন", slug: "ai-design", icon: "🎨" },
    use_cases: ["image"],
    features_bn: ["Image generation presets", "Asset ও mockup workflow", "Creative variations"],
    pros: ["Visual asset workflow ভালো", "Free experimentation possible", "Design iteration দ্রুত"],
    cons: ["Final brand asset polish দরকার", "Prompt/result consistency test করতে হয়"],
    faq: [{ q: "Leonardo AI কার জন্য?", a: "Designer, game creator, marketer এবং visual content creator-দের জন্য।" }],
    badge: "trending",
    rating: 4.5,
    review_count: 1,
    view_count: 0,
  },
  {
    id: "curated-gamma",
    name: "Gamma",
    slug: "gamma",
    tagline_bn: "AI দিয়ে presentation, pitch deck, proposal ও visual document বানানোর জন্য।",
    description_bn:
      "Gamma দ্রুত presentation, pitch deck, report, proposal এবং visual document তৈরি করতে সাহায্য করে। freelancer proposal, startup deck, course outline বা client report বানাতে এটি সময় বাঁচায়।",
    pricing: "freemium",
    pricing_type: "freemium",
    website_url: "https://gamma.app/",
    logo_url: "",
    status: "published",
    category_slug: "ai-presentation",
    categories: { name_bn: "প্রেজেন্টেশন", slug: "ai-presentation", icon: "📊" },
    use_cases: ["presentation", "writing"],
    features_bn: ["AI deck generation", "Visual document layout", "Proposal ও report structure"],
    pros: ["Deck বানানো দ্রুত", "Non-designer friendly", "Client-facing document polished লাগে"],
    cons: ["Final copy ও data manually verify দরকার", "Brand template customize করতে হতে পারে"],
    faq: [{ q: "Gamma কী কাজে সবচেয়ে ভালো?", a: "Presentation, pitch deck, proposal এবং report draft দ্রুত বানাতে।" }],
    badge: "best_value",
    rating: 4.5,
    review_count: 1,
    view_count: 0,
  },
  {
    id: "curated-notion-ai",
    name: "Notion AI",
    slug: "notion-ai",
    tagline_bn: "Notes, docs, team wiki, project planning ও knowledge base-এর জন্য AI workspace assistant।",
    description_bn:
      "Notion AI writing, summary, action item, project planning এবং team knowledge base workflow-তে ব্যবহারযোগ্য। content calendar, client notes, SOP, meeting notes বা research database রাখতে চাইলে এটি practical।",
    pricing: "paid",
    pricing_type: "paid",
    website_url: "https://www.notion.com/product/ai",
    logo_url: "",
    status: "published",
    category_slug: "ai-productivity",
    categories: { name_bn: "প্রোডাক্টিভিটি", slug: "ai-productivity", icon: "⚡" },
    use_cases: ["writing", "research", "automation"],
    features_bn: ["Notes summary", "Project planning", "Knowledge base writing"],
    pros: ["Workspace-এর ভেতরেই AI", "Team documentation সহজ", "Content planning-এ useful"],
    cons: ["Notion workflow না থাকলে value কম", "Large team permission policy ঠিক রাখা দরকার"],
    faq: [{ q: "Notion AI কার জন্য?", a: "Team, creator, freelancer এবং যারা notes/docs/project planning Notion-এ করেন।" }],
    badge: "popular",
    rating: 4.4,
    review_count: 1,
    view_count: 0,
  },
  {
    id: "curated-github-copilot",
    name: "GitHub Copilot",
    slug: "github-copilot",
    tagline_bn: "Code completion, test writing, code explanation ও IDE-assisted development-এর জন্য।",
    description_bn:
      "GitHub Copilot developer workflow-তে inline code suggestion, test generation, code explanation এবং repetitive coding কাজ দ্রুত করতে সাহায্য করে। professional developer, student এবং agency team-দের জন্য useful।",
    pricing: "paid",
    pricing_type: "paid",
    website_url: "https://github.com/features/copilot",
    logo_url: "",
    status: "published",
    category_slug: "ai-development",
    categories: { name_bn: "ডেভেলপমেন্ট", slug: "ai-development", icon: "💻" },
    use_cases: ["coding"],
    features_bn: ["Inline code suggestions", "Test ও docs drafting", "IDE chat support"],
    pros: ["Coding speed বাড়ে", "Boilerplate কমে", "Popular IDE support আছে"],
    cons: ["Generated code review জরুরি", "License/security policy মাথায় রাখতে হয়"],
    faq: [{ q: "Copilot কি beginner-দের জন্য ভালো?", a: "হ্যাঁ, learning support দেয়; তবে output বুঝে ব্যবহার করা জরুরি।" }],
    badge: "editors_choice",
    rating: 4.7,
    review_count: 1,
    view_count: 0,
  },
  {
    id: "curated-bolt-new",
    name: "Bolt.new",
    slug: "bolt-new",
    tagline_bn: "Prompt থেকে web app prototype, frontend এবং full-stack experiment বানানোর জন্য AI dev tool।",
    description_bn:
      "Bolt.new দ্রুত prototype, landing page, SaaS demo বা small full-stack app scaffold করতে সাহায্য করে। founder, freelancer এবং developer-দের idea validation workflow-তে এটি useful।",
    pricing: "freemium",
    pricing_type: "freemium",
    website_url: "https://bolt.new/",
    logo_url: "",
    status: "published",
    category_slug: "ai-development",
    categories: { name_bn: "ডেভেলপমেন্ট", slug: "ai-development", icon: "💻" },
    use_cases: ["coding", "automation"],
    features_bn: ["Prompt-to-app generation", "Frontend prototype", " দ্রুত iteration"],
    pros: ["Prototype খুব দ্রুত", "Idea validation সহজ", "Non-linear development flow support করে"],
    cons: ["Production hardening আলাদা কাজ", "Generated code review দরকার"],
    faq: [{ q: "Bolt.new কী কাজে ব্যবহার করব?", a: "MVP, demo, landing page বা quick web app prototype বানাতে।" }],
    badge: "trending",
    rating: 4.4,
    review_count: 1,
    view_count: 0,
  },
  {
    id: "curated-lovable",
    name: "Lovable",
    slug: "lovable",
    tagline_bn: "Natural language দিয়ে web app, UI এবং product prototype তৈরির জন্য AI builder।",
    description_bn:
      "Lovable prompt থেকে product UI, web app flow এবং prototype তৈরি করতে সাহায্য করে। founder, product manager, designer এবং freelancer যারা দ্রুত clickable/product demo বানাতে চান তাদের জন্য useful।",
    pricing: "freemium",
    pricing_type: "freemium",
    website_url: "https://lovable.dev/",
    logo_url: "",
    status: "published",
    category_slug: "ai-development",
    categories: { name_bn: "ডেভেলপমেন্ট", slug: "ai-development", icon: "💻" },
    use_cases: ["coding", "presentation"],
    features_bn: ["Prompt-based app builder", "UI generation", "Product prototype workflow"],
    pros: ["Founder-friendly", "UI quickly তৈরি হয়", "Demo বানাতে সময় কম লাগে"],
    cons: ["Complex backend manually refine দরকার", "Production security review দরকার"],
    faq: [{ q: "Lovable কি developer ছাড়াই app বানায়?", a: "Prototype বানাতে সাহায্য করে; production launch-এর আগে technical review দরকার।" }],
    badge: "new",
    rating: 4.4,
    review_count: 1,
    view_count: 0,
  },
  {
    id: "curated-n8n",
    name: "n8n",
    slug: "n8n",
    tagline_bn: "Self-hostable workflow automation, AI agent workflow ও app integration-এর জন্য।",
    description_bn:
      "n8n technical/no-code hybrid automation platform। form থেকে CRM, Telegram notification, AI summarization, data sync, lead enrichment বা internal tool workflow বানাতে এটি শক্তিশালী। self-host option থাকায় cost/control-sensitive team-এর জন্য ভালো।",
    pricing: "freemium",
    pricing_type: "freemium",
    website_url: "https://n8n.io/",
    logo_url: "",
    status: "published",
    category_slug: "ai-automation",
    categories: { name_bn: "অটোমেশন", slug: "ai-automation", icon: "⚙️" },
    use_cases: ["automation"],
    features_bn: ["Workflow automation", "AI/API integration", "Self-host option"],
    pros: ["Flexible automation", "Self-host control", "Developer-friendly"],
    cons: ["Complex workflow setup skill লাগে", "Hosting/maintenance বুঝতে হয়"],
    faq: [{ q: "n8n আর Zapier-এর পার্থক্য কী?", a: "Zapier সহজ managed option; n8n বেশি flexible এবং self-host control দেয়।" }],
    badge: "best_value",
    rating: 4.6,
    review_count: 1,
    view_count: 0,
  },
  {
    id: "curated-make",
    name: "Make",
    slug: "make",
    tagline_bn: "Visual automation, app integration ও business workflow design-এর জন্য no-code platform।",
    description_bn:
      "Make visual scenario builder দিয়ে marketing, sales, support, data sync এবং AI-assisted workflow automate করতে সাহায্য করে। ছোট business ও agency operations automation-এর জন্য practical।",
    pricing: "freemium",
    pricing_type: "freemium",
    website_url: "https://www.make.com/",
    logo_url: "",
    status: "published",
    category_slug: "ai-automation",
    categories: { name_bn: "অটোমেশন", slug: "ai-automation", icon: "⚙️" },
    use_cases: ["automation"],
    features_bn: ["Visual scenario builder", "App integrations", "AI workflow chaining"],
    pros: ["Visual flow বোঝা সহজ", "Operations automation ভালো", "Complex branching support করে"],
    cons: ["Scenario design ভুল হলে data issue হতে পারে", "Usage pricing বুঝে নিতে হয়"],
    faq: [{ q: "Make কী কাজে ভালো?", a: "Lead routing, data sync, notification, reporting এবং multi-step business automation-এ।" }],
    badge: "popular",
    rating: 4.5,
    review_count: 1,
    view_count: 0,
  },
  {
    id: "curated-fireflies",
    name: "Fireflies.ai",
    slug: "fireflies-ai",
    tagline_bn: "Meeting recording, transcription, summary ও action item tracking-এর জন্য AI meeting assistant।",
    description_bn:
      "Fireflies.ai Zoom/Google Meet/Teams meeting transcribe করে summary, action item ও searchable notes তৈরি করতে সাহায্য করে। agency, sales team, remote team এবং client meeting-heavy workflow-তে useful।",
    pricing: "freemium",
    pricing_type: "freemium",
    website_url: "https://fireflies.ai/",
    logo_url: "",
    status: "published",
    category_slug: "ai-productivity",
    categories: { name_bn: "প্রোডাক্টিভিটি", slug: "ai-productivity", icon: "⚡" },
    use_cases: ["voice", "automation"],
    features_bn: ["Meeting transcription", "AI summary", "Action item extraction"],
    pros: ["Meeting notes manual কাজ কমায়", "Client follow-up সহজ", "Searchable archive তৈরি হয়"],
    cons: ["Recording consent দরকার", "Accent/language accuracy test করা উচিত"],
    faq: [{ q: "Fireflies.ai কার জন্য?", a: "Remote team, agency, sales/support team এবং যারা অনেক meeting করেন।" }],
    badge: "best_value",
    rating: 4.4,
    review_count: 1,
    view_count: 0,
  },
  {
    id: "curated-descript",
    name: "Descript",
    slug: "descript",
    tagline_bn: "Podcast, video editing, transcript-based edit ও AI voice workflow-এর জন্য creator tool।",
    description_bn:
      "Descript text-based audio/video editing, transcript correction, screen recording, overdub-style workflow এবং podcast/video content editing সহজ করে। creator, educator এবং marketing team-এর জন্য useful।",
    pricing: "freemium",
    pricing_type: "freemium",
    website_url: "https://www.descript.com/",
    logo_url: "",
    status: "published",
    category_slug: "ai-video",
    categories: { name_bn: "ভিডিও", slug: "ai-video", icon: "🎬" },
    use_cases: ["video", "voice"],
    features_bn: ["Transcript-based editing", "Audio cleanup", "Screen/video content workflow"],
    pros: ["Editing workflow সহজ", "Podcast/video দুটোতেই useful", "Text edit-এর মতো media edit করা যায়"],
    cons: ["Advanced video effects-এর জন্য আলাদা editor লাগতে পারে", "Voice features policy দেখে ব্যবহার করা উচিত"],
    faq: [{ q: "Descript কী কাজে সেরা?", a: "Podcast, explainer video, course video এবং transcript-based editing workflow-তে।" }],
    badge: "popular",
    rating: 4.4,
    review_count: 1,
    view_count: 0,
  },
  {
    id: "curated-jasper",
    name: "Jasper",
    slug: "jasper",
    tagline_bn: "Marketing copy, brand voice, campaign content ও team writing workflow-এর জন্য AI writing platform।",
    description_bn:
      "Jasper marketing team ও agency workflow-এর জন্য campaign copy, ad copy, landing page draft, email sequence এবং brand voice-consistent content তৈরিতে সাহায্য করে।",
    pricing: "paid",
    pricing_type: "paid",
    website_url: "https://www.jasper.ai/",
    logo_url: "",
    status: "published",
    category_slug: "ai-writing",
    categories: { name_bn: "রাইটিং", slug: "ai-writing", icon: "✍️" },
    use_cases: ["writing"],
    features_bn: ["Marketing copy templates", "Brand voice support", "Campaign content workflow"],
    pros: ["Marketing-focused", "Team workflow support", "Brand consistency-তে useful"],
    cons: ["General free assistant-এর তুলনায় cost বেশি", "Final fact/copy review দরকার"],
    faq: [{ q: "Jasper কার জন্য?", a: "Marketing team, agency, copywriter এবং paid campaign content workflow-এর জন্য।" }],
    badge: "editors_choice",
    rating: 4.3,
    review_count: 1,
    view_count: 0,
  },
];

export function curatedToolMatchesCategory(tool: CuratedTool, categorySlug?: string) {
  if (!categorySlug) return true;
  if (categorySlug === "ai-tools") return tool.category_slug.startsWith("ai-") || tool.categories.slug.startsWith("ai-");
  return tool.category_slug === categorySlug || tool.categories.slug === categorySlug;
}

export function getCuratedTools(options: { pricing?: string; categorySlug?: string; query?: string } = {}) {
  const query = options.query?.trim().toLowerCase();
  return CURATED_TOOLS.filter((tool) => {
    if (options.pricing && tool.pricing !== options.pricing && tool.pricing_type !== options.pricing) return false;
    if (options.categorySlug && !curatedToolMatchesCategory(tool, options.categorySlug)) return false;
    if (!query) return true;
    const haystack = [
      tool.name,
      tool.slug,
      tool.tagline_bn,
      tool.description_bn,
      tool.categories.name_bn,
      ...tool.use_cases,
      ...tool.features_bn,
    ]
      .join(" ")
      .toLowerCase();
    return haystack.includes(query);
  });
}

export function mergeCuratedTools<T extends { slug?: string }>(tools: T[] | null | undefined, curated = CURATED_TOOLS) {
  const existing = new Set((tools || []).map((tool) => tool.slug).filter(Boolean));
  return [...(tools || []), ...curated.filter((tool) => !existing.has(tool.slug))];
}

export function findCuratedTool(slug: string) {
  return CURATED_TOOLS.find((tool) => tool.slug === slug) || null;
}
